name: Update yarn.lock
on:
  push:
    branches:
      - main
    paths:
      - 'package.json' # 只在package.json变更时触发
  workflow_dispatch: # 允许手动触发

jobs:
  update-yarn-lock:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史，支持提交

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies and update yarn.lock
        run: yarn install

      - name: Check for changes in yarn.lock
        id: check_changes
        run: |
          if git diff --quiet yarn.lock; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add yarn.lock
          git commit -m "chore: update yarn.lock [skip ci]"

      - name: Push changes
        if: steps.check_changes.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
